development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio1_development
  username: root
  password: password1119
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: PLTexchange

production:
  <<: *defaults
  database: PLTexchange
